# Generated by Django 3.1.7 on 2021-03-23 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0005_auto_20210307_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='innovator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='innovator', to=settings.AUTH_USER_MODEL),
        ),
    ]
