# Generated by Django 3.1.7 on 2021-03-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_innovator'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='innovator',
            table='innovator',
        ),
    ]
