# Generated by Django 3.1.7 on 2021-03-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_auto_20210307_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
