# Generated by Django 3.1.7 on 2021-03-07 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import innovator.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myadmin', '0009_auto_20210307_0809'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('small_description', models.TextField()),
                ('large_description', models.TextField()),
                ('setup_price', models.CharField(max_length=20)),
                ('setup_duration', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='uploads/', validators=[innovator.validators.validate_file_extension])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'In Active')], max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'idea',
            },
        ),
    ]
