# Generated by Django 3.1.7 on 2021-03-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'In Active')], default='active', max_length=30),
        ),
    ]
